stages:
  - build
  - push
  - release

default:
  tags:
    - shared-runner
  image:
    name: docker:git
    entrypoint: ['']

variables:
  IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  LATEST_IMAGE: $CI_REGISTRY_IMAGE:latest

build:
  stage: build
  script:
    - docker build -t $IMAGE .

push:
  stage: push
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker tag $IMAGE $LATEST_IMAGE
    - docker push $LATEST_IMAGE
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
